TMP

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,44 +6,45 @@ permissions:
 on: [push, pull_request]
 
 jobs:
-  build-linux:
-    name: Build and test Linux executable
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        arch: [amd64, armv7, aarch64, ppc64le, riscv64, i386]
-
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Prepare
-        run: chmod u+x .github/workflows/*.sh
-
-      - name: Build for matrix.arch == amd64
-        if: ${{ matrix.arch == 'amd64' }}
-        run: |
-          sudo .github/workflows/generic-build.sh ${{ matrix.arch }}
-          sudo .github/workflows/ci-run-tests.sh
-          wget https://codecov.io/bash || true
-          bash bash -s /tmp/kcov-kcov || true
-
-      - name: Build for matrix.arch == i386
-        if: ${{ matrix.arch == 'i386' }}
-        run: |
-          chmod u+x ./.github/workflows/setup-i386.sh
-          sudo .github/workflows/setup-i386.sh
-          sudo schroot -c mychroot -- ./.github/workflows/generic-build.sh ${{ matrix.arch }}
-
-      - name: Build for matrix.arch == armv7, aarch64, ppc64le
-        if: ${{ matrix.arch == 'armv7' || matrix.arch == 'aarch64' || matrix.arch == 'ppc64le' || matrix.arch == 'riscv64' }}
-        uses: uraimo/run-on-arch-action@v2
-        with:
-          arch: ${{ matrix.arch }}
-          distro: ubuntu22.04
-          run: |
-            .github/workflows/generic-build.sh ${{ matrix.arch }}
-
+#  build-linux:
+#    name: Build and test Linux executable
+#    runs-on: ubuntu-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        arch: [amd64]
+#        #, armv7, aarch64, ppc64le, riscv64, i386]
+#
+#    steps:
+#      - uses: actions/checkout@v4
+#
+#      - name: Prepare
+#        run: chmod u+x .github/workflows/*.sh
+#
+#      - name: Build for matrix.arch == amd64
+#        if: ${{ matrix.arch == 'amd64' }}
+#        run: |
+#          sudo .github/workflows/generic-build.sh ${{ matrix.arch }}
+#          sudo .github/workflows/ci-run-tests.sh
+#          wget https://codecov.io/bash || true
+#          bash bash -s /tmp/kcov-kcov || true
+#
+#      - name: Build for matrix.arch == i386
+#        if: ${{ matrix.arch == 'i386' }}
+#        run: |
+#          chmod u+x ./.github/workflows/setup-i386.sh
+#          sudo .github/workflows/setup-i386.sh
+#          sudo schroot -c mychroot -- ./.github/workflows/generic-build.sh ${{ matrix.arch }}
+#
+#      - name: Build for matrix.arch == armv7, aarch64, ppc64le
+#        if: ${{ matrix.arch == 'armv7' || matrix.arch == 'aarch64' || matrix.arch == 'ppc64le' || matrix.arch == 'riscv64' }}
+#        uses: uraimo/run-on-arch-action@v2
+#        with:
+#          arch: ${{ matrix.arch }}
+#          distro: ubuntu22.04
+#          run: |
+#            .github/workflows/generic-build.sh ${{ matrix.arch }}
+#
   build-osx:
     name: Build OSX executable (macos-latest)
     runs-on: macos-latest
@@ -64,30 +65,30 @@ jobs:
           sudo .github/workflows/osx-build.sh
           sudo .github/workflows/ci-run-tests.sh
 
-  build-freebsd:
-    runs-on: ubuntu-22.04
-    name: Build and test FreeBSD executable
-    steps:
-    - uses: actions/checkout@v4
-    - name: FreeBSD
-      id: test
-      uses: vmactions/freebsd-vm@v1
-      with:
-        usesh: true
-        prepare: pkg install -y binutils cmake elfutils python bash git python2
-        run: |
-          chmod u+x .github/workflows/freebsd-build.sh .github/workflows/ci-run-tests.sh
-          .github/workflows/freebsd-build.sh x86_64
-          .github/workflows/ci-run-tests.sh
+#  build-freebsd:
+#    runs-on: ubuntu-22.04
+#    name: Build and test FreeBSD executable
+#    steps:
+#    - uses: actions/checkout@v4
+#    - name: FreeBSD
+#      id: test
+#      uses: vmactions/freebsd-vm@v1
+#      with:
+#        usesh: true
+#        prepare: pkg install -y binutils cmake elfutils python bash git python2
+#        run: |
+#          chmod u+x .github/workflows/freebsd-build.sh .github/workflows/ci-run-tests.sh
+#          .github/workflows/freebsd-build.sh x86_64
+#          .github/workflows/ci-run-tests.sh
 
   build-and-push-docker-image:
     name: Build and push to Docker Hub
-    needs: [build-linux, build-osx, build-freebsd]
+    needs: []
     runs-on: ubuntu-latest
     environment:
       name: "Docker Hub"
       url: https://hub.docker.com/r/kcov/kcov
-    if: github.ref == 'refs/heads/master'
+    #if: github.ref == 'refs/heads/master'
     steps:
     - uses: actions/checkout@v4
       with:
@@ -112,7 +113,6 @@ jobs:
           docker buildx build \
             --tag $IMAGE_TAG \
             --platform $PLATFORM \
-            --push \
             .
       env:
         IMAGE_TAG: kcov/kcov:latest
@@ -131,4 +131,4 @@ jobs:
         # - linux/mips64le
         # No users on this platform:
         # - linux/ppc64le
-        PLATFORM: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/riscv64
+        PLATFORM: linux/amd64
